apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: rh-summit-warsaw
build:
  artifacts:
    - image: piomin/rh-summit-warsaw
      jib:
        args:
          - -Pjib
          - -DskipTests
manifests:
  rawYaml:
    - k8s/deployment.yaml
deploy:
  kubectl: {}